
[dep]
dependencies = [
    "requests", "selenium", "beautifulsoup4", "pylint",
    "openpyxl", "smtplib" ]

[project.optional-dependencies]
dev = [
    "requests", "selenium", "beautifulsoup4", "pylint",
    "openpyxl", "smtplib" ]

[tool.setuptools]
py-modules = []

[tool.coverage.run]
omit = [
    "*/conftest.py", "*/test*", # omit test files
]

[tool.coverage.report]
fail_under = 80